# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermod < Formula
  desc "Hermod – P2P File Sharing for Campus Networks"
  homepage "https://github.com/MFZNK05/DFS-Go"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.3.0/hermod_0.3.0_darwin_amd64.tar.gz"
      sha256 "d5081ed06cf1886c37b8b3a8913249cdce88fd3f87ebbed50ee45abf81baf905"

      define_method(:install) do
        bin.install "hermod"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.3.0/hermod_0.3.0_darwin_arm64.tar.gz"
      sha256 "9b6269b8dcc692ae5ead7e5de93406ef5a9f042f32a7d2eef337947ea662b96d"

      define_method(:install) do
        bin.install "hermod"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.3.0/hermod_0.3.0_linux_amd64.tar.gz"
      sha256 "a1f58a7f27f1c6eafcfa2011b66fd2be671a40e44545258a086cdb029cfb4ab8"
      define_method(:install) do
        bin.install "hermod"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.3.0/hermod_0.3.0_linux_arm64.tar.gz"
      sha256 "acb5f5d5b98c65a8f094aa6e0a823374a2f51a4934219d31bbdc2765e59f659e"
      define_method(:install) do
        bin.install "hermod"
      end
    end
  end
end
