# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermond < Formula
  desc "Hermond – P2P File Sharing for Campus Networks"
  homepage "https://github.com/MFZNK05/DFS-Go"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.0/hermond_0.2.0_darwin_amd64.tar.gz"
      sha256 "8c3a4d62bb3c7f199c1ad56dca129162b9598b6892925e0b9263bd46870a2306"

      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.0/hermond_0.2.0_darwin_arm64.tar.gz"
      sha256 "e9b82f85b289fdf08987a355b4739b10c79962fdbd22a64de348cf7f4e76559d"

      define_method(:install) do
        bin.install "hermond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.0/hermond_0.2.0_linux_amd64.tar.gz"
      sha256 "5171708ae8af18e2ae4826a527016b003e27b6d13c411c0968dac3ae55be93f3"
      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.0/hermond_0.2.0_linux_arm64.tar.gz"
      sha256 "b8a0b7638462ffd043352b1381ff6a5c909a428ba5c99b93b3e7f26d98abb79b"
      define_method(:install) do
        bin.install "hermond"
      end
    end
  end
end
