# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermond < Formula
  desc "Hermond – P2P File Sharing for Campus Networks"
  homepage "https://github.com/MFZNK05/DFS-Go"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.1.4/hermond_0.1.4_darwin_amd64.tar.gz"
      sha256 "aee616c1492595f4341cc4922650c24cb30b7c36f3e80ac8da828b99e41d0c78"

      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.1.4/hermond_0.1.4_darwin_arm64.tar.gz"
      sha256 "1acd3180e001f919893739ca9a514a9813163468a6200f70c8087a033ba4505f"

      define_method(:install) do
        bin.install "hermond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.1.4/hermond_0.1.4_linux_amd64.tar.gz"
      sha256 "709b7f85ccd7ae12474ca2bf2aebcb4565f2387658cce29924a8ad39f7eac29c"
      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.1.4/hermond_0.1.4_linux_arm64.tar.gz"
      sha256 "23c03801eb8895439b2e4f585852ba0b16a11fe616da98a2b8f7785812a7b2e6"
      define_method(:install) do
        bin.install "hermond"
      end
    end
  end
end
