# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hermond < Formula
  desc "Hermond – P2P File Sharing for Campus Networks"
  homepage "https://github.com/MFZNK05/DFS-Go"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.2/hermond_0.2.2_darwin_amd64.tar.gz"
      sha256 "4c9ec4a7d1933a89155a3ba30890cd104e3bdb692c3c35c2db667dd0702993c3"

      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.2/hermond_0.2.2_darwin_arm64.tar.gz"
      sha256 "e18d52968e5002a466b7af7fd99265f218bdd62eb23f7cead1a0ba4b02e5ba27"

      define_method(:install) do
        bin.install "hermond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.2/hermond_0.2.2_linux_amd64.tar.gz"
      sha256 "c656a69b08cee87f09bb6eaffa1cfdb612171832cd16d8740d234c0410686f1b"
      define_method(:install) do
        bin.install "hermond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MFZNK05/DFS-Go/releases/download/v0.2.2/hermond_0.2.2_linux_arm64.tar.gz"
      sha256 "2a45283d0ccd3ad38c07d976b936dc03751511f345c6c9ff4fc20a08799224b6"
      define_method(:install) do
        bin.install "hermond"
      end
    end
  end
end
